# Build Options
#   change yes to no to disable

AUDIO_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no
RGBLIGHT_SUPPORTED = no
SERIAL_DRIVER = vendor
SOFT_SERIAL_ENABLE = no
CONSOLE_ENABLE = yes 
ENCODER_ENABLE = no
